# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cf916eb1173de127dde5babcce8f2ff5ebed1a6929293e9231133cd91d26334d1f4e8926b61ace7dc73ae64384c60a75466e9d27376a11df5f161a9e113a747

test:
  secret_key_base: 6ce6939e125f17e062ab1fe2077aa9d12740bcb0cf41b730041a4e423e2bc2a548e8e1c8072d7ab90e8ff3e9cec2bbfee6e76fe1df60281051bad93a7be1472a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
